project:
  type: website
  output-dir: docs/
  resources: 
    - "data/examples/*.geojson"
    - "data/*.geojson"
    - "assets/styles/*.css"

website:
  title: "Safer Parks"
  cookie-consent:
    type: express
    style: headline
  navbar:
    left:
      - href: content/index.qmd
        text: Home
      - content/dashboard-info.qmd
      - content/refactoring-dashboard.qmd

format:
  html:
    theme: [assets/styles/custom.scss, cosmo]
    css: [assets/styles/styles.css, assets/styles/fonts.css]
    toc: true



