project:
  type: website
  output-dir: docs/

website:
  title: "Safer Parks"
  cookie-consent: true
  navbar:
    left:
      - href: content/index.qmd
        text: Home
      - content/dashboard-info.qmd
      - content/full-screen.qmd

format:
  html:
    theme: [assets/styles/custom.scss, cosmo]
    css: [assets/styles/styles.css, assets/styles/fonts.css]
    toc: true



